const mongoose = require("mongoose")

/**
 * Batch Schema
 * Represents a group of users with associated polynomial equations
 */
const batchSchema = new mongoose.Schema(
    {
        // _id is auto-generated by MongoDB as ObjectId (primary key)

        // Array of string representations of BigInt values
        // JavaScript BigInt values are stored as strings to preserve precision
        equation: {
            type: [String],
            required: true,
            validate: {
                validator: function (value) {
                    // Validate that equation is an array
                    return Array.isArray(value)
                },
                message: "Equation must be an array",
            },
        },
    },
    {
        timestamps: true, // Automatically add createdAt and updatedAt fields
    }
)

// Export the Batch model
const Batch = mongoose.model("Batch", batchSchema)

module.exports = Batch
