const mongoose = require("mongoose")

/**
 * Event Schema
 * Represents a RabbitMQ event received from the User Management System (UMS)
 * Used for audit trail and event replay capabilities
 */
const eventSchema = new mongoose.Schema(
    {
        // _id is auto-generated by MongoDB as ObjectId (primary key)

        // Routing key from RabbitMQ message (e.g., 'organization.created')
        routingKey: {
            type: String,
            required: true,
            index: true,
        },

        // Parsed JSON payload from the message
        payload: {
            type: mongoose.Schema.Types.Mixed,
            required: true,
        },

        // Timestamp when the message was received
        receivedAt: {
            type: Date,
            default: Date.now,
            index: true,
        },

        // Timestamp when the message processing completed
        processedAt: {
            type: Date,
        },

        // Processing status of the event
        status: {
            type: String,
            enum: ["received", "processing", "completed", "failed"],
            default: "received",
        },

        // Error message if processing failed
        error: {
            type: String,
        },
    },
    {
        timestamps: true, // Automatically add createdAt and updatedAt fields
    }
)

// Export the Event model
const Event = mongoose.model("Event", eventSchema)

module.exports = Event
