const mongoose = require("mongoose")
const crypto = require("crypto")

/**
 * Organization Schema
 * Represents a business organization with wallet address and salt values
 */
const organizationSchema = new mongoose.Schema(
    {
        // _id is auto-generated by MongoDB as ObjectId (primary key)

        // Unique organization ID - must be provided by the user
        org_id: {
            type: Number,
            required: true,
            unique: true,
        },

        // Unique wallet address - must be provided by the user
        wallet_address: {
            type: String,
            required: true,
            unique: true,
        },

        // Unique organization salt - auto-generated using crypto.randomBytes
        org_salt: {
            type: String,
            required: false,
        },
    },
    {
        timestamps: true, // Automatically add createdAt and updatedAt fields
    }
)

// Add unique index for org_salt
organizationSchema.index({ org_salt: 1 }, { unique: true })

// Pre-save hook to auto-generate org_salt
organizationSchema.pre("save", function (next) {
    // Only generate if this is a new document and fields are not already set
    if (this.isNew) {
        // Auto-generate org_salt using crypto.randomBytes if not provided
        if (!this.org_salt) {
            // Generate 32 bytes of random data and convert to hex string
            this.org_salt = crypto.randomBytes(32).toString("hex")
        }
    }

    next()
})

// Export the Organization model
const Organization = mongoose.model("Organization", organizationSchema)

module.exports = Organization
