const mongoose = require("mongoose")
const crypto = require("crypto")
const { v4: uuidv4 } = require("uuid")

/**
 * Organization Schema
 * Represents a business organization with unique reference keys and salt values
 */
const organizationSchema = new mongoose.Schema(
    {
        // _id is auto-generated by MongoDB as ObjectId (primary key)

        // Unique reference key - auto-generated using UUID v4
        reference_key: {
            type: String,
            required: false,
        },

        // Unique organization salt - auto-generated using crypto.randomBytes
        org_salt: {
            type: String,
            required: false,
        },
    },
    {
        timestamps: true, // Automatically add createdAt and updatedAt fields
    }
)

// Add unique indexes for reference_key and org_salt
organizationSchema.index({ reference_key: 1 }, { unique: true })
organizationSchema.index({ org_salt: 1 }, { unique: true })

// Pre-save hook to auto-generate reference_key and org_salt
organizationSchema.pre("save", function (next) {
    // Only generate if this is a new document and fields are not already set
    if (this.isNew) {
        // Auto-generate reference_key using UUID v4 if not provided
        if (!this.reference_key) {
            this.reference_key = uuidv4()
        }

        // Auto-generate org_salt using crypto.randomBytes if not provided
        if (!this.org_salt) {
            // Generate 32 bytes of random data and convert to hex string
            this.org_salt = crypto.randomBytes(32).toString("hex")
        }
    }

    next()
})

// Export the Organization model
const Organization = mongoose.model("Organization", organizationSchema)

module.exports = Organization
