const mongoose = require("mongoose")

/**
 * User Schema
 * Represents a member with balance, fraud score, and optional reference number
 */
const userSchema = new mongoose.Schema(
    {
        // _id is auto-generated by MongoDB as ObjectId (primary key)

        // Foreign key reference to Batch model
        batch_id: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Batch",
            required: true,
        },

        // User balance - must be non-negative
        balance: {
            type: Number,
            default: 0,
            min: [0, "Balance cannot be negative"],
            required: true,
        },

        // Unique reference number - can be null
        // Sparse index allows multiple null values while enforcing uniqueness for non-null values
        reference_number: {
            type: String,
            required: false,
        },

        // Fraud score - must be between 0 and 1 inclusive
        // 1 = highest risk, 0 = lowest risk
        fraud_score: {
            type: Number,
            default: 1,
            min: [0, "Fraud score must be at least 0"],
            max: [1, "Fraud score must be at most 1"],
            required: true,
        },
    },
    {
        timestamps: true, // Automatically add createdAt and updatedAt fields
    }
)

// Add sparse unique index for reference_number
// This allows multiple null values while enforcing uniqueness for non-null values
userSchema.index({ reference_number: 1 }, { unique: true, sparse: true })

// Export the User model
const User = mongoose.model("User", userSchema)

module.exports = User
